# Generated by Django 5.1.7 on 2025-03-30 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0002_auto_20200517_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtors',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
